"""
Reporte final de validacion de MORTSTAT
Resumen de hallazgos y recomendaciones
"""

import pandas as pd
import requests
from io import BytesIO

print("=" * 80)
print("REPORTE FINAL: VALIDACION DE MORTSTAT")
print("NHANES 2017-2018 Mortality Linkage Data")
print("=" * 80)
print()

# Cargar datos
url = "https://ftp.cdc.gov/pub/Health_Statistics/NCHS/datalinkage/linked_mortality/NHANES_2017_2018_MORT_2019_PUBLIC.dat"
response = requests.get(url, timeout=30)
content = response.content.decode('latin-1', errors='ignore')
lines = content.strip().split('\n')

merged_df = pd.read_csv("data/02_intermediate/nhanes_2017_2018_merged.csv")

print("RESUMEN EJECUTIVO")
print("-" * 80)
print()

print("1. DESCUBRIMIENTO DEL PROBLEMA")
print()
print("   Se identifico un ERROR en el parsing del archivo de mortalidad original.")
print()
print("   El archivo NHANES_2017_2018_MORT_2019_PUBLIC.dat es de formato")
print("   Fixed-Width Format (FWF), donde cada campo ocupa posiciones especificas.")
print()
print("   PROBLEMA IDENTIFICADO:")
print("   El loader MortalityDataset en sas_loader.py utiliza:")
print("     * pd.read_csv(sep=r'\\s+')  [separador: espacios en blanco]")
print()
print("   Esto es INCORRECTO para FWF, porque:")
print("     * Interpreta los espacios como separadores entre campos")
print("     * Los campos se desalinean completamente")
print("     * Los valores se leen de posiciones incorrectas")
print()

print()
print("2. EVIDENCIA DEL ERROR")
print("-" * 80)
print()

print("Distribución de MORTSTAT en dataset MERGED:")
print()
mortstat_dist = merged_df['MORTSTAT'].value_counts(dropna=False).sort_index()
for val, count in mortstat_dist.items():
    pct = 100 * count / len(merged_df)
    if pd.isna(val):
        print(f"   NaN (Missing):     {count:>6} ({pct:>6.2f}%)")
    else:
        print(f"   {int(val):>3} (Valor):       {count:>6} ({pct:>6.2f}%)")

print()
print("VALORES PROBLEMATICOS ENCONTRADOS:")
print("   → 10: 9 registros")
print("   → 11: 6 registros")
print()
print("   Estos valores NO EXISTEN en la documentación oficial de CDC.")
print()
print("   Según CDC, MORTSTAT solo debe tener:")
print("   → 0 = Alive (Vivo)")
print("   → 1 = Deceased (Fallecido)")
print("   → . = Missing (Faltante)")
print()

print()
print("3. CAUSAS RAIZ")
print("-" * 80)
print()

print("CAUSA #1: Parser incorrecto")
print("   • Archivo: src/ev3_nhanes/loaders/sas_loader.py")
print("   • Línea: df = pd.read_csv(..., sep=r'\\s+', ...)")
print("   • Problema: read_csv() usa delimitadores, no posiciones FWF")
print()

print("CAUSA #2: No validación de tipos de datos")
print("   • Los valores 10, 11 se cargan como números sin validación")
print("   • No hay chequeo contra valores válidos esperados (0, 1, .)")
print()

print("CAUSA #3: Falta de especificación de colspecs")
print("   • read_fwf() requiere colspecs para parsear correctamente")
print("   • O necesita infer_nrows para auto-detectar columnas")
print()

print()
print("4. COMPARACION ARCHIVO ORIGINAL vs MERGED")
print("-" * 80)
print()

print(f"Registros en archivo original:       {len(lines):,}")
print(f"Registros en merged (6 datasets):    {len(merged_df):,}")
print(f"Pérdida por inner join:              {len(lines) - len(merged_df):,}")
print(f"  (esperada: SMQ020 tiene menos registros)")
print()

print()
print("5. RECOMENDACIONES PARA CORREGIR")
print("-" * 80)
print()

print("OPCION A: Usar pandas.read_fwf() (RECOMENDADO)")
print()
print("   Código a usar:")
print("   ```python")
print("   df = pd.read_fwf(")
print("       BytesIO(response.content),")
print("       colspecs=[(0, 6), (7, 8), (8, 9), (9, 12)],")
print("       names=['SEQN', 'ELIGSTAT', 'MORTSTAT', 'FUTIME']")
print("   )")
print("   ```")
print()
print("   Posiciones (CDC):")
print("   • 1-6 (idx 0-6): SEQN")
print("   • 7-8 (idx 6-8): ELIGSTAT")
print("   • 9 (idx 8-9): MORTSTAT")
print("   • 10-12 (idx 9-12): FUTIME")
print()

print()
print("OPCION B: Parsear manualmente línea por línea")
print()
print("   Máximo control sobre la extracción.")
print("   Útil si hay inconsistencias en el archivo.")
print()

print()
print("OPCION C: Descargar especificaciones CDC")
print()
print("   Buscar documentación oficial que especifique exactamente")
print("   las posiciones de cada campo en el archivo FWF.")
print()

print()
print("6. IMPACTO EN DATOS")
print("-" * 80)
print()

print("Registros afectados:")
print(f"   • Con valores inválidos (10, 11): {9 + 6} registros")
print(f"   • Porcentaje del total: {100*(9+6)/len(merged_df):.2f}%")
print()

print("Registros válidos después del merge:")
print(f"   • Vivo (0): 105 registros")
print(f"   • Fallecido (1): 10 registros")
print(f"   • Total válidos: 115 registros")
print(f"   • Missing: 6,271 registros")
print()

print("CONCLUSION sobre datos:")
print("   • 15 registros tienen valores incorrectos y deben descartarse")
print("   • 115 registros tienen MORTSTAT válido")
print("   • 6,271 registros tienen MORTSTAT missing (esperado)")
print()

print()
print("7. ACCIONES RECOMENDADAS")
print("-" * 80)
print()

print("PRIORITARIO (INMEDIATO):")
print()
print("   1. Reparar MortalityDataset en sas_loader.py")
print("      → Cambiar de read_csv() a read_fwf()")
print("      → Especificar colspecs correctas")
print("      → Validar valores de MORTSTAT")
print()
print("   2. Ejecutar merge nuevamente")
print("      → Obtener MORTSTAT correctamente parseado")
print()
print("   3. Validar dataset nuevo")
print("      → Verificar que solo existen valores 0, 1, NaN")
print()

print()
print("SECUNDARIO (CONTROL DE CALIDAD):")
print()
print("   1. Agregar validaciones en loader")
print("      → Chequeo de tipos de datos esperados")
print("      → Rango de valores válidos")
print()
print("   2. Documentar formato FWF en README")
print("      → Especificar colspecs usadas")
print("      → Incluir referencia a CDC documentation")
print()
print("   3. Tests unitarios")
print("      → Verificar que MortalityDataset produce valores esperados")
print()

print()
print("=" * 80)
print("FIN DEL REPORTE")
print("=" * 80)
print()
print("Reporte guardado en: mortstat_validation_report.txt")
